AWSTemplateFormatVersion: "2010-09-09"
Description: ECR Repository For the Docker Image

Resources:
  ECRRepo:
    Type: AWS::ECR::Repository
    Properties: 
      EncryptionConfiguration: 
        EncryptionType: AES256
      ImageScanningConfiguration: 
        ScanOnPush: true
      ImageTagMutability: IMMUTABLE
      RepositoryName: rest-api
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - "arn:aws:iam::864227929192:user/admin1"
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
      Tags: 
        - Key: environment
          Value: development

Outputs:
  ECRRepoArn:
    Description: ServiceArn of ECR Repo
    Value: !GetAtt ECRRepo.Arn